[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-power-recommendation-engine"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "Flask==3.0.0",
    "pandas==2.1.4",
    "numpy>=1.26.0",
    "requests==2.31.0"
]
